class HairClipRunner {
    public static void main(String[] args) {

        HairClip h1 = new HairClip();
        h1.brand = "Clippy";
        h1.material = "Plastic";
        h1.color = "Pink";
        h1.size = "Small";
        h1.isDecorative = true;
        h1.price = 15.99;
		System.out.println("the brand name is "+h1.brand);
		System.out.println("the material is "+h1.material);
		System.out.println("the color is "+h1.color);
		System.out.println("the size is "+h1.size);
		System.out.println("the isDecorative is "+h1.isDecorative);
		System.out.println("the price is "+h1.price);

        HairClip h2 = new HairClip();
        h2.brand = "Snapz";
        h2.material = "Metal";
        h2.color = "Black";
        h2.size = "Medium";
        h2.isDecorative = false;
        h2.price = 10.50;
System.out.println("the brand name is "+h2.brand);
		System.out.println("the material is "+h2.material);
		System.out.println("the color is "+h2.color);
		System.out.println("the size is "+h2.size);
		System.out.println("the isDecorative is "+h2.isDecorative);
		System.out.println("the price is "+h2.price);
		
        HairClip h3 = new HairClip();
        h3.brand = "Goody";
        h3.material = "Resin";
        h3.color = "Red";
        h3.size = "Large";
        h3.isDecorative = true;
        h3.price = 18.25;
		System.out.println("the brand name is "+h3.brand);
		System.out.println("the material is "+h3.material);
		System.out.println("the color is "+h3.color);
		System.out.println("the size is "+h3.size);
		System.out.println("the isDecorative is "+h3.isDecorative);
		System.out.println("the price is "+h3.price);

        HairClip h4 = new HairClip();
        h4.brand = "Pearlia";
        h4.material = "Metal";
        h4.color = "Silver";
        h4.size = "Medium";
        h4.isDecorative = true;
        h4.price = 25.00;
		System.out.println("the brand name is "+h4.brand);
		System.out.println("the material is "+h4.material);
		System.out.println("the color is "+h4.color);
		System.out.println("the size is "+h4.size);
		System.out.println("the isDecorative is "+h4.isDecorative);
		System.out.println("the price is "+h4.price);

        HairClip h5 = new HairClip();
        h5.brand = "FunkyClips";
        h5.material = "Plastic";
        h5.color = "Yellow";
        h5.size = "Small";
        h5.isDecorative = true;
        h5.price = 12.75;
		System.out.println("the brand name is "+h5.brand);
		System.out.println("the material is "+h5.material);
		System.out.println("the color is "+h5.color);
		System.out.println("the size is "+h5.size);
		System.out.println("the isDecorative is "+h5.isDecorative);
		System.out.println("the price is "+h5.price);

        HairClip h6 = new HairClip();
        h6.brand = "Stylo";
        h6.material = "Acrylic";
        h6.color = "Green";
        h6.size = "Medium";
        h6.isDecorative = false;
        h6.price = 9.99;
		System.out.println("the brand name is "+h6.brand);
		System.out.println("the material is "+h6.material);
		System.out.println("the color is "+h6.color);
		System.out.println("the size is "+h6.size);
		System.out.println("the isDecorative is "+h6.isDecorative);
		System.out.println("the price is "+h6.price);

        HairClip h7 = new HairClip();
        h7.brand = "Beautica";
        h7.material = "Metal";
        h7.color = "Bronze";
        h7.size = "Large";
        h7.isDecorative = true;
        h7.price = 30.00;
		System.out.println("the brand name is "+h7.brand);
		System.out.println("the material is "+h7.material);
		System.out.println("the color is "+h7.color);
		System.out.println("the size is "+h7.size);
		System.out.println("the isDecorative is "+h7.isDecorative);
		System.out.println("the price is "+h7.price);

        HairClip h8 = new HairClip();
        h8.brand = "ChicClip";
        h8.material = "Plastic";
        h8.color = "White";
        h8.size = "Small";
        h8.isDecorative = true;
        h8.price = 11.49;
		System.out.println("the brand name is "+h8.brand);
		System.out.println("the material is "+h8.material);
		System.out.println("the color is "+h8.color);
		System.out.println("the size is "+h8.size);
		System.out.println("the isDecorative is "+h8.isDecorative);
		System.out.println("the price is "+h8.price);

        HairClip h9 = new HairClip();
        h9.brand = "Glitz";
        h9.material = "Plastic";
        h9.color = "Purple";
        h9.size = "Medium";
        h9.isDecorative = true;
        h9.price = 16.00;
		System.out.println("the brand name is "+h9.brand);
		System.out.println("the material is "+h9.material);
		System.out.println("the color is "+h9.color);
		System.out.println("the size is "+h9.size);
		System.out.println("the isDecorative is "+h9.isDecorative);
		System.out.println("the price is "+h9.price);

        HairClip h10 = new HairClip();
        h10.brand = "BobbyTrendz";
        h10.material = "Metal";
        h10.color = "Grey";
        h10.size = "Small";
        h10.isDecorative = false;
        h10.price = 8.25;
		System.out.println("the brand name is "+h10.brand);
		System.out.println("the material is "+h10.material);
		System.out.println("the color is "+h10.color);
		System.out.println("the size is "+h10.size);
		System.out.println("the isDecorative is "+h10.isDecorative);
		System.out.println("the price is "+h10.price);

        HairClip h11 = new HairClip();
        h11.brand = "TwistX";
        h11.material = "Plastic";
        h11.color = "Orange";
        h11.size = "Large";
        h11.isDecorative = false;
        h11.price = 13.90;
		System.out.println("the brand name is "+h11.brand);
		System.out.println("the material is "+h11.material);
		System.out.println("the color is "+h11.color);
		System.out.println("the size is "+h11.size);
		System.out.println("the isDecorative is "+h11.isDecorative);
		System.out.println("the price is "+h11.price);

        HairClip h12 = new HairClip();
        h12.brand = "ElegantPins";
        h12.material = "Metal";
        h12.color = "Gold";
        h12.size = "Small";
        h12.isDecorative = true;
        h12.price = 22.45;
		System.out.println("the brand name is "+h12.brand);
		System.out.println("the material is "+h12.material);
		System.out.println("the color is "+h12.color);
		System.out.println("the size is "+h12.size);
		System.out.println("the isDecorative is "+h12.isDecorative);
		System.out.println("the price is "+h12.price);

        HairClip h13 = new HairClip();
        h13.brand = "Cutie";
        h13.material = "Silicone";
        h13.color = "Blue";
        h13.size = "Medium";
        h13.isDecorative = true;
        h13.price = 17.00;
		System.out.println("the brand name is "+h13.brand);
		System.out.println("the material is "+h13.material);
		System.out.println("the color is "+h13.color);
		System.out.println("the size is "+h13.size);
		System.out.println("the isDecorative is "+h13.isDecorative);
		System.out.println("the price is "+h13.price);

        HairClip h14 = new HairClip();
        h14.brand = "DivaGrip";
        h14.material = "Plastic";
        h14.color = "Magenta";
        h14.size = "Large";
        h14.isDecorative = false;
        h14.price = 14.75;
		System.out.println("the brand name is "+h14.brand);
		System.out.println("the material is "+h14.material);
		System.out.println("the color is "+h14.color);
		System.out.println("the size is "+h14.size);
		System.out.println("the isDecorative is "+h14.isDecorative);
		System.out.println("the price is "+h14.price);

        HairClip h15 = new HairClip();
        h15.brand = "GripIt";
        h15.material = "Acrylic";
        h15.color = "Navy";
        h15.size = "Medium";
        h15.isDecorative = false;
        h15.price = 10.00;
		System.out.println("the brand name is "+h15.brand);
		System.out.println("the material is "+h15.material);
		System.out.println("the color is "+h15.color);
		System.out.println("the size is "+h15.size);
		System.out.println("the isDecorative is "+h15.isDecorative);
		System.out.println("the price is "+h15.price);

        HairClip h16 = new HairClip();
        h16.brand = "FloraStyle";
        h16.material = "Plastic";
        h16.color = "Rose Gold";
        h16.size = "Small";
        h16.isDecorative = true;
        h16.price = 21.20;
		System.out.println("the brand name is "+h16.brand);
		System.out.println("the material is "+h16.material);
		System.out.println("the color is "+h16.color);
		System.out.println("the size is "+h16.size);
		System.out.println("the isDecorative is "+h16.isDecorative);
		System.out.println("the price is "+h16.price);

        HairClip h17 = new HairClip();
        h17.brand = "ZenClips";
        h17.material = "Wood";
        h17.color = "Brown";
        h17.size = "Medium";
        h17.isDecorative = true;
        h17.price = 26.80;
		System.out.println("the brand name is "+h17.brand);
		System.out.println("the material is "+h17.material);
		System.out.println("the color is "+h17.color);
		System.out.println("the size is "+h17.size);
		System.out.println("the isDecorative is "+h17.isDecorative);
		System.out.println("the price is "+h17.price);

        HairClip h18 = new HairClip();
        h18.brand = "ShineIt";
        h18.material = "Metal";
        h18.color = "Silver";
        h18.size = "Large";
        h18.isDecorative = true;
        h18.price = 29.99;

System.out.println("the brand name is "+h18.brand);
		System.out.println("the material is "+h18.material);
		System.out.println("the color is "+h18.color);
		System.out.println("the size is "+h18.size);
		System.out.println("the isDecorative is "+h18.isDecorative);
		System.out.println("the price is "+h18.price);
        HairClip h19 = new HairClip();
        h19.brand = "Nailie";
        h19.material = "Plastic";
        h19.color = "Turquoise";
        h19.size = "Medium";
        h19.isDecorative = false;
        h19.price = 15.35;
		System.out.println("the brand name is "+h19.brand);
		System.out.println("the material is "+h19.material);
		System.out.println("the color is "+h19.color);
		System.out.println("the size is "+h19.size);
		System.out.println("the isDecorative is "+h19.isDecorative);
		System.out.println("the price is "+h19.price);

        HairClip h20 = new HairClip();
        h20.brand = "PixieClips";
        h20.material = "Fabric";
        h20.color = "Cream";
        h20.size = "Small";
        h20.isDecorative = true;
        h20.price = 18.75;
		System.out.println("the brand name is "+h20.brand);
		System.out.println("the material is "+h20.material);
		System.out.println("the color is "+h20.color);
		System.out.println("the size is "+h20.size);
		System.out.println("the isDecorative is "+h20.isDecorative);
		System.out.println("the price is "+h20.price);
    }
}
