class InvitationCardRunner {
    public static void main(String[] args) {

        InvitationCard c1 = new InvitationCard();
        c1.title = "Wedding Bells";
        c1.color = "Golden";
        c1.occasion = "Wedding";
        c1.size = "A5";
        c1.price = 20.0;
        c1.isPrinted = true;
        System.out.println("c1.title: " + c1.title);
        System.out.println("c1.color: " + c1.color);
        System.out.println("c1.occasion: " + c1.occasion);
        System.out.println("c1.size: " + c1.size);
        System.out.println("c1.price: " + c1.price);
        System.out.println("c1.isPrinted: " + c1.isPrinted);

        InvitationCard c2 = new InvitationCard();
        c2.title = "Birthday Bash";
        c2.color = "Blue";
        c2.occasion = "Birthday";
        c2.size = "A4";
        c2.price = 15.0;
        c2.isPrinted = false;
        System.out.println("c2.title: " + c2.title);
        System.out.println("c2.color: " + c2.color);
        System.out.println("c2.occasion: " + c2.occasion);
        System.out.println("c2.size: " + c2.size);
        System.out.println("c2.price: " + c2.price);
        System.out.println("c2.isPrinted: " + c2.isPrinted);

        InvitationCard c3 = new InvitationCard();
        c3.title = "Baby Shower";
        c3.color = "Pink";
        c3.occasion = "Baby Shower";
        c3.size = "A6";
        c3.price = 18.0;
        c3.isPrinted = true;
        System.out.println("c3.title: " + c3.title);
		 System.out.println("c2.color: " + c3.color);
        System.out.println("c2.occasion: " + c3.occasion);
        System.out.println("c2.size: " + c3.size);
        System.out.println("c2.price: " + c3.price);
        System.out.println("c2.isPrinted: " + c3.isPrinted);

        InvitationCard c4 = new InvitationCard();
        c4.title = "Housewarming";
        c4.color = "Beige";
        c4.occasion = "Housewarming";
        c4.size = "A5";
        c4.price = 25.0;
        c4.isPrinted = true;
        System.out.println("c4.title: " + c4.title);
		 System.out.println("c2.color: " + c4.color);
        System.out.println("c2.occasion: " + c4.occasion);
        System.out.println("c2.size: " + c4.size);
        System.out.println("c2.price: " + c4.price);
        System.out.println("c2.isPrinted: " + c4.isPrinted);

        InvitationCard c5 = new InvitationCard();
        c5.title = "Anniversary Party";
        c5.color = "Red";
        c5.occasion = "Anniversary";
        c5.size = "A4";
        c5.price = 30.0;
        c5.isPrinted = false;
        System.out.println("c5.title: " + c5.title);
		 System.out.println("c2.color: " + c5.color);
        System.out.println("c2.occasion: " + c5.occasion);
        System.out.println("c2.size: " + c5.size);
        System.out.println("c2.price: " + c5.price);
        System.out.println("c2.isPrinted: " + c5.isPrinted);

        InvitationCard c6 = new InvitationCard();
        c6.title = "Engagement Invite";
        c6.color = "Lavender";
        c6.occasion = "Engagement";
        c6.size = "A5";
        c6.price = 22.0;
        c6.isPrinted = true;
        System.out.println("c6.title: " + c6.title);
		 System.out.println("c2.color: " + c6.color);
        System.out.println("c2.occasion: " + c6.occasion);
        System.out.println("c2.size: " + c6.size);
        System.out.println("c2.price: " + c6.price);
        System.out.println("c2.isPrinted: " + c6.isPrinted);

        InvitationCard c7 = new InvitationCard();
        c7.title = "Graduation";
        c7.color = "Black & Gold";
        c7.occasion = "Graduation";
        c7.size = "A6";
        c7.price = 19.5;
        c7.isPrinted = true;
        System.out.println("c7.title: " + c7.title);
		 System.out.println("c2.color: " + c7.color);
        System.out.println("c2.occasion: " + c7.occasion);
        System.out.println("c2.size: " + c7.size);
        System.out.println("c2.price: " + c7.price);
        System.out.println("c2.isPrinted: " + c7.isPrinted);

        InvitationCard c8 = new InvitationCard();
        c8.title = "Retirement Farewell";
        c8.color = "Grey";
        c8.occasion = "Retirement";
        c8.size = "A5";
        c8.price = 21.0;
        c8.isPrinted = true;
        System.out.println("c8.title: " + c8.title);
		 System.out.println("c2.color: " + c8.color);
        System.out.println("c2.occasion: " + c8.occasion);
        System.out.println("c2.size: " + c8.size);
        System.out.println("c2.price: " + c8.price);
        System.out.println("c2.isPrinted: " + c8.isPrinted);

        InvitationCard c9 = new InvitationCard();
        c9.title = "Reception Invite";
        c9.color = "Cream";
        c9.occasion = "Reception";
        c9.size = "A4";
        c9.price = 27.0;
        c9.isPrinted = false;
        System.out.println("c9.title: " + c9.title);
		 System.out.println("c2.color: " + c9.color);
        System.out.println("c2.occasion: " + c9.occasion);
        System.out.println("c2.size: " + c9.size);
        System.out.println("c2.price: " + c9.price);
        System.out.println("c2.isPrinted: " + c9.isPrinted);

        InvitationCard c10 = new InvitationCard();
        c10.title = "Naming Ceremony";
        c10.color = "Light Blue";
        c10.occasion = "Naming";
        c10.size = "A6";
        c10.price = 17.0;
        c10.isPrinted = true;
        System.out.println("c10.title: " + c10.title);
		 System.out.println("c2.color: " + c10.color);
        System.out.println("c2.occasion: " + c10.occasion);
        System.out.println("c2.size: " + c10.size);
        System.out.println("c2.price: " + c10.price);
        System.out.println("c2.isPrinted: " + c10.isPrinted);

        InvitationCard c11 = new InvitationCard();
        c11.title = "Sangeet Night";
        c11.color = "Yellow";
        c11.occasion = "Sangeet";
        c11.size = "A5";
        c11.price = 20.0;
        c11.isPrinted = true;
        System.out.println("c11.title: " + c11.title);
		 System.out.println("c2.color: " + c11.color);
        System.out.println("c2.occasion: " + c11.occasion);
        System.out.println("c2.size: " + c11.size);
        System.out.println("c2.price: " + c11.price);
        System.out.println("c2.isPrinted: " + c11.isPrinted);

        InvitationCard c12 = new InvitationCard();
        c12.title = "Farewell Party";
        c12.color = "Navy Blue";
        c12.occasion = "Farewell";
        c12.size = "A4";
        c12.price = 24.0;
        c12.isPrinted = true;
        System.out.println("c12.title: " + c12.title);
		 System.out.println("c2.color: " + c12.color);
        System.out.println("c2.occasion: " + c12.occasion);
        System.out.println("c2.size: " + c12.size);
        System.out.println("c2.price: " + c12.price);
        System.out.println("c2.isPrinted: " + c12.isPrinted);

        InvitationCard c13 = new InvitationCard();
        c13.title = "Reunion Party";
        c13.color = "Teal";
        c13.occasion = "Reunion";
        c13.size = "A5";
        c13.price = 20.5;
        c13.isPrinted = false;
        System.out.println("c13.title: " + c13.title);
		 System.out.println("c2.color: " + c13.color);
        System.out.println("c2.occasion: " + c13.occasion);
        System.out.println("c2.size: " + c13.size);
        System.out.println("c2.price: " + c13.price);
        System.out.println("c2.isPrinted: " + c13.isPrinted);

        InvitationCard c14 = new InvitationCard();
        c14.title = "Welcome Party";
        c14.color = "White";
        c14.occasion = "Welcome";
        c14.size = "A4";
        c14.price = 18.5;
        c14.isPrinted = true;
        System.out.println("c14.title: " + c14.title);
		 System.out.println("c2.color: " + c14.color);
        System.out.println("c2.occasion: " + c14.occasion);
        System.out.println("c2.size: " + c14.size);
        System.out.println("c2.price: " + c14.price);
        System.out.println("c2.isPrinted: " + c14.isPrinted);

        InvitationCard c15 = new InvitationCard();
        c15.title = "Office Opening";
        c15.color = "Brown";
        c15.occasion = "Business";
        c15.size = "A5";
        c15.price = 23.0;
        c15.isPrinted = false;
        System.out.println("c15.title: " + c15.title);
		 System.out.println("c2.color: " + c15.color);
        System.out.println("c2.occasion: " + c15.occasion);
        System.out.println("c2.size: " + c15.size);
        System.out.println("c2.price: " + c15.price);
        System.out.println("c2.isPrinted: " + c15.isPrinted);

        InvitationCard c16 = new InvitationCard();
        c16.title = "Annual Day";
        c16.color = "Orange";
        c16.occasion = "School Function";
        c16.size = "A6";
        c16.price = 16.0;
        c16.isPrinted = true;
        System.out.println("c16.title: " + c16.title);
		 System.out.println("c2.color: " + c16.color);
        System.out.println("c2.occasion: " + c16.occasion);
        System.out.println("c2.size: " + c16.size);
        System.out.println("c2.price: " + c16.price);
        System.out.println("c2.isPrinted: " + c16.isPrinted);

        InvitationCard c17 = new InvitationCard();
        c17.title = "Sports Day";
        c17.color = "Sky Blue";
        c17.occasion = "School Event";
        c17.size = "A5";
        c17.price = 19.0;
        c17.isPrinted = true;
        System.out.println("c17.title: " + c17.title);
		 System.out.println("c2.color: " + c17.color);
        System.out.println("c2.occasion: " + c17.occasion);
        System.out.println("c2.size: " + c17.size);
        System.out.println("c2.price: " + c17.price);
        System.out.println("c2.isPrinted: " + c17.isPrinted);

        InvitationCard c18 = new InvitationCard();
        c18.title = "Book Launch";
        c18.color = "Black";
        c18.occasion = "Literary";
        c18.size = "A5";
        c18.price = 25.5;
        c18.isPrinted = true;
        System.out.println("c18.title: " + c18.title);
		 System.out.println("c2.color: " + c18.color);
        System.out.println("c2.occasion: " + c18.occasion);
        System.out.println("c2.size: " + c18.size);
        System.out.println("c2.price: " + c18.price);
        System.out.println("c2.isPrinted: " + c18.isPrinted);

        InvitationCard c19 = new InvitationCard();
        c19.title = "Art Exhibition";
        c19.color = "Multicolor";
        c19.occasion = "Art";
        c19.size = "A4";
        c19.price = 30.0;
        c19.isPrinted = false;
        System.out.println("c19.title: " + c19.title);
		 System.out.println("c2.color: " + c19.color);
        System.out.println("c2.occasion: " + c19.occasion);
        System.out.println("c2.size: " + c19.size);
        System.out.println("c2.price: " + c19.price);
        System.out.println("c2.isPrinted: " + c19.isPrinted);

        InvitationCard c20 = new InvitationCard();
        c20.title = "Cultural Night";
        c20.color = "Purple";
        c20.occasion = "Cultural";
        c20.size = "A5";
        c20.price = 22.5;
        c20.isPrinted = true;
        System.out.println("c20.title: " + c20.title);
		 System.out.println("c2.color: " + c20.color);
        System.out.println("c2.occasion: " + c20.occasion);
        System.out.println("c2.size: " + c20.size);
        System.out.println("c2.price: " + c20.price);
        System.out.println("c2.isPrinted: " + c20.isPrinted);
    }
}
