class BladeRunner {
    public static void main(String args[]) {
        Blade b1 = new Blade();
        b1.brand = "Gillette";
        b1.type = "Razor";
        b1.size = "Small";
        b1.price = 99.0;
        b1.isStainlessSteel = true;
        b1.usage = "Shaving";
        System.out.println("b1.brand: " + b1.brand);
        System.out.println("b1.type: " + b1.type);
        System.out.println("b1.size: " + b1.size);
        System.out.println("b1.price: " + b1.price);
        System.out.println("b1.isStainlessSteel: " + b1.isStainlessSteel);
        System.out.println("b1.usage: " + b1.usage);
	
        Blade b2 = new Blade(); 
		b2.brand = "SuperMax";
		b2.type = "Blade";
		b2.size = "M";
		b2.price = 49.0;
		b2.isStainlessSteel = false; 
		b2.usage = "Trimming";
		 System.out.println("b1.brand: " + b2.brand);
        System.out.println("b1.type: " + b2.type);
        System.out.println("b1.size: " + b2.size);
        System.out.println("b1.price: " + b2.price);
        System.out.println("b1.isStainlessSteel: " + b2.isStainlessSteel);
        System.out.println("b1.usage: " + b2.usage);
		
        Blade b3 = new Blade();
		b3.brand = "Laser";
		b3.type = "Razor"; 
		b3.size = "L"; 
		b3.price = 59.0; 
		b3.isStainlessSteel = true; 
		b3.usage = "Beard";
		 System.out.println("b1.brand: " + b3.brand);
        System.out.println("b1.type: " + b3.type);
        System.out.println("b1.size: " + b3.size);
        System.out.println("b1.price: " + b3.price);
        System.out.println("b1.isStainlessSteel: " + b3.isStainlessSteel);
        System.out.println("b1.usage: " + b3.usage);
		
        Blade b4 = new Blade();
		b4.brand = "Dorco"; 
		b4.type = "Blade";
		b4.size = "S"; 
		b4.price = 39.0;
		b4.isStainlessSteel = false; 
		b4.usage = "Face";
		 System.out.println("b1.brand: " + b4.brand);
        System.out.println("b1.type: " + b4.type);
        System.out.println("b1.size: " + b4.size);
        System.out.println("b1.price: " + b4.price);
        System.out.println("b1.isStainlessSteel: " + b4.isStainlessSteel);
        System.out.println("b1.usage: " + b4.usage);
		
        Blade b5 = new Blade(); 
		b5.brand = "Wilkinson";
		b5.type = "Razor";
		b5.size = "XL";
		b5.price = 129.0;
		b5.isStainlessSteel = true;
		b5.usage = "Body";
		 System.out.println("b1.brand: " + b5.brand);
        System.out.println("b1.type: " + b5.type);
        System.out.println("b1.size: " + b5.size);
        System.out.println("b1.price: " + b5.price);
        System.out.println("b1.isStainlessSteel: " + b5.isStainlessSteel);
        System.out.println("b1.usage: " + b5.usage);
		
        Blade b6 = new Blade();
		b6.brand = "Feather";
		b6.type = "Blade";
		b6.size = "S"; 
		b6.price = 89.0;
		b6.isStainlessSteel = true;
		b6.usage = "Sensitive Skin";
		 System.out.println("b1.brand: " + b6.brand);
        System.out.println("b1.type: " + b6.type);
        System.out.println("b1.size: " + b6.size);
        System.out.println("b1.price: " + b6.price);
        System.out.println("b1.isStainlessSteel: " + b6.isStainlessSteel);
        System.out.println("b1.usage: " + b6.usage);
		
        Blade b7 = new Blade();
		b7.brand = "Bic"; 
		b7.type = "Razor";
		b7.size = "M";
		b7.price = 59.0;
		b7.isStainlessSteel = false;
		b7.usage = "Legs";
		 System.out.println("b1.brand: " + b7.brand);
        System.out.println("b1.type: " + b7.type);
        System.out.println("b1.size: " + b7.size);
        System.out.println("b1.price: " + b7.price);
        System.out.println("b1.isStainlessSteel: " + b7.isStainlessSteel);
        System.out.println("b1.usage: " + b7.usage);
		
        Blade b8 = new Blade();
		b8.brand = "Astra";
		b8.type = "Blade";
		b8.size = "S"; 
		b8.price = 69.0;
		b8.isStainlessSteel = true; 
		b8.usage = "Chest";
		 System.out.println("b1.brand: " + b8.brand);
        System.out.println("b1.type: " + b8.type);
        System.out.println("b1.size: " + b8.size);
        System.out.println("b1.price: " + b8.price);
        System.out.println("b1.isStainlessSteel: " + b8.isStainlessSteel);
        System.out.println("b1.usage: " + b8.usage);
		
        Blade b9 = new Blade();
		b9.brand = "Kai";
		b9.type = "Razor";
		b9.size = "L";
		b9.price = 109.0; 
		b9.isStainlessSteel = true; 
		b9.usage = "Armpit";
		 System.out.println("b1.brand: " + b9.brand);
        System.out.println("b1.type: " + b9.type);
        System.out.println("b1.size: " + b9.size);
        System.out.println("b1.price: " + b9.price);
        System.out.println("b1.isStainlessSteel: " + b9.isStainlessSteel);
        System.out.println("b1.usage: " + b9.usage);
		
        Blade b10 = new Blade(); 
		b10.brand = "Derby";
		b10.type = "Blade"; 
		b10.size = "M"; 
		b10.price = 49.0;
		b10.isStainlessSteel = false; 
		b10.usage = "General";
		 System.out.println("b1.brand: " + b10.brand);
        System.out.println("b1.type: " + b10.type);
        System.out.println("b1.size: " + b10.size);
        System.out.println("b1.price: " + b10.price);
        System.out.println("b1.isStainlessSteel: " + b10.isStainlessSteel);
        System.out.println("b1.usage: " + b10.usage);
		
        Blade b11 = new Blade();
		b11.brand = "Persona";
		b11.type = "Razor"; 
		b11.size = "S";
		b11.price = 95.0;
		b11.isStainlessSteel = true;
		b11.usage = "Shaving";
		 System.out.println("b1.brand: " + b11.brand);
        System.out.println("b1.type: " + b11.type);
        System.out.println("b1.size: " + b11.size);
        System.out.println("b1.price: " + b11.price);
        System.out.println("b1.isStainlessSteel: " + b11.isStainlessSteel);
        System.out.println("b1.usage: " + b11.usage);
		
        Blade b12 = new Blade();
		b12.brand = "Merkur"; 
		b12.type = "Blade";
		b12.size = "S";
		b12.price = 85.0; 
		b12.isStainlessSteel = true;
		b12.usage = "Beard Trim";
		 System.out.println("b1.brand: " + b12.brand);
        System.out.println("b1.type: " + b12.type);
        System.out.println("b1.size: " + b12.size);
        System.out.println("b1.price: " + b12.price);
        System.out.println("b1.isStainlessSteel: " + b12.isStainlessSteel);
        System.out.println("b1.usage: " + b12.usage);
		
        Blade b13 = new Blade();
		b13.brand = "Treet"; 
		b13.type = "Blade";
		b13.size = "M"; 
		b13.price = 39.0; 
		b13.isStainlessSteel = false; 
		b13.usage = "Legs";
		 System.out.println("b1.brand: " + b13.brand);
        System.out.println("b1.type: " + b13.type);
        System.out.println("b1.size: " + b13.size);
        System.out.println("b1.price: " + b13.price);
        System.out.println("b1.isStainlessSteel: " + b13.isStainlessSteel);
        System.out.println("b1.usage: " + b13.usage);
		
        Blade b14 = new Blade(); 
		b14.brand = "Voskhod"; 
		b14.type = "Blade"; 
		b14.size = "S";
		b14.price = 55.0;
		b14.isStainlessSteel = true; 
		b14.usage = "Neck";
		 System.out.println("b1.brand: " + b14.brand);
        System.out.println("b1.type: " + b14.type);
        System.out.println("b1.size: " + b14.size);
        System.out.println("b1.price: " + b14.price);
        System.out.println("b1.isStainlessSteel: " + b14.isStainlessSteel);
        System.out.println("b1.usage: " + b14.usage);
		
        Blade b15 = new Blade();
		b15.brand = "Rapira"; 
		b15.type = "Blade";
		b15.size = "L";
		b15.price = 60.0; 
		b15.isStainlessSteel = true; 
		b15.usage = "Face";
		 System.out.println("b1.brand: " + b15.brand);
        System.out.println("b1.type: " + b15.type);
        System.out.println("b1.size: " + b15.size);
        System.out.println("b1.price: " + b15.price);
        System.out.println("b1.isStainlessSteel: " + b15.isStainlessSteel);
        System.out.println("b1.usage: " + b15.usage);
		
        Blade b16 = new Blade();
		b16.brand = "Bluebird";
		b16.type = "Blade";
		b16.size = "S"; 
		b16.price = 45.0; 
		b16.isStainlessSteel = false; 
		b16.usage = "Body Hair";
		 System.out.println("b1.brand: " + b16.brand);
        System.out.println("b1.type: " + b16.type);
        System.out.println("b1.size: " + b16.size);
        System.out.println("b1.price: " + b16.price);
        System.out.println("b1.isStainlessSteel: " + b16.isStainlessSteel);
        System.out.println("b1.usage: " + b16.usage);
		
        Blade b17 = new Blade();
		b17.brand = "Shark"; 
		b17.type = "Razor";
		b17.size = "XL"; 
		b17.price = 120.0; 
		b17.isStainlessSteel = true;
		b17.usage = "Face";
		 System.out.println("b1.brand: " + b17.brand);
        System.out.println("b1.type: " + b17.type);
        System.out.println("b1.size: " + b17.size);
        System.out.println("b1.price: " + b17.price);
        System.out.println("b1.isStainlessSteel: " + b17.isStainlessSteel);
        System.out.println("b1.usage: " + b17.usage);
		
        Blade b18 = new Blade();
		b18.brand = "Croma";
		b18.type = "Blade";
		b18.size = "S"; 
		b18.price = 70.0;
		b18.isStainlessSteel = true;
		b18.usage = "Trimming";
		 System.out.println("b1.brand: " + b18.brand);
        System.out.println("b1.type: " + b18.type);
        System.out.println("b1.size: " + b18.size);
        System.out.println("b1.price: " + b18.price);
        System.out.println("b1.isStainlessSteel: " + b18.isStainlessSteel);
        System.out.println("b1.usage: " + b18.usage);
		
        Blade b19 = new Blade();
		b19.brand = "Indian"; 
		b19.type = "Razor"; 
		b19.size = "M"; 
		b19.price = 50.0; b19.isStainlessSteel = false;
		b19.usage = "Basic";
		 System.out.println("b1.brand: " + b19.brand);
        System.out.println("b1.type: " + b19.type);
        System.out.println("b1.size: " + b19.size);
        System.out.println("b1.price: " + b19.price);
        System.out.println("b1.isStainlessSteel: " + b19.isStainlessSteel);
        System.out.println("b1.usage: " + b19.usage);
		
        Blade b20 = new Blade(); 
		b20.brand = "Shark"; 
		b20.type = "Razor";
		b20.size = "XL"; 
		b20.price = 120.0; 
		b20.isStainlessSteel = true;
		b20.usage = "Face";
		 System.out.println("b1.brand: " + b20.brand);
        System.out.println("b1.type: " + b20.type);
        System.out.println("b1.size: " + b20.size);
        System.out.println("b1.price: " + b20.price);
        System.out.println("b1.isStainlessSteel: " + b20.isStainlessSteel);
        System.out.println("b1.usage: " + b20.usage);
    }
}
