class FestivalsRunner {
    public static void main(String[] args) {
        System.out.println("Main Started - Festivals Data");

        Festivals festival1 = new Festivals();
        festival1.name = "Diwali";
        festival1.mainReligionCulture = "Hindu";
        festival1.typicalSeason = "Autumn";
        festival1.approximateDurationDays = 5;
        festival1.primaryCelebrationActivity = "Lighting lamps, fireworks, prayers, sweets";
        festival1.geographicalFocus = "Pan-India, Global";
        System.out.println("Name: " + festival1.name);
        System.out.println("Main Religion/Culture: " + festival1.mainReligionCulture);
        System.out.println("Typical Season: " + festival1.typicalSeason);
        System.out.println("Approximate Duration (Days): " + festival1.approximateDurationDays);
        System.out.println("Primary Celebration Activity: " + festival1.primaryCelebrationActivity);
        System.out.println("Geographical Focus: " + festival1.geographicalFocus);
        System.out.println();

        Festivals festival2 = new Festivals();
        festival2.name = "Eid al-Fitr";
        festival2.mainReligionCulture = "Islam";
        festival2.typicalSeason = "Varies (Lunar Calendar)";
        festival2.approximateDurationDays = 1;
        festival2.primaryCelebrationActivity = "Prayers, feasting, charity, new clothes";
        festival2.geographicalFocus = "Global";
        System.out.println("Name: " + festival2.name);
        System.out.println("Main Religion/Culture: " + festival2.mainReligionCulture);
        System.out.println("Typical Season: " + festival2.typicalSeason);
        System.out.println("Approximate Duration (Days): " + festival2.approximateDurationDays);
        System.out.println("Primary Celebration Activity: " + festival2.primaryCelebrationActivity);
        System.out.println("Geographical Focus: " + festival2.geographicalFocus);
        System.out.println();

        Festivals festival3 = new Festivals();
        festival3.name = "Christmas";
        festival3.mainReligionCulture = "Christian";
        festival3.typicalSeason = "Winter";
        festival3.approximateDurationDays = 1;
        festival3.primaryCelebrationActivity = "Church services, gift-giving, family meals";
        festival3.geographicalFocus = "Global";
        System.out.println("Name: " + festival3.name);
        System.out.println("Main Religion/Culture: " + festival3.mainReligionCulture);
        System.out.println("Typical Season: " + festival3.typicalSeason);
        System.out.println("Approximate Duration (Days): " + festival3.approximateDurationDays);
        System.out.println("Primary Celebration Activity: " + festival3.primaryCelebrationActivity);
        System.out.println("Geographical Focus: " + festival3.geographicalFocus);
        System.out.println();

        Festivals festival4 = new Festivals();
        festival4.name = "Holi";
        festival4.mainReligionCulture = "Hindu";
        festival4.typicalSeason = "Spring";
        festival4.approximateDurationDays = 2;
        festival4.primaryCelebrationActivity = "Playing with colors, bonfires, sweets";
        festival4.geographicalFocus = "Pan-India, Nepal";
        System.out.println("Name: " + festival4.name);
        System.out.println("Main Religion/Culture: " + festival4.mainReligionCulture);
        System.out.println("Typical Season: " + festival4.typicalSeason);
        System.out.println("Approximate Duration (Days): " + festival4.approximateDurationDays);
        System.out.println("Primary Celebration Activity: " + festival4.primaryCelebrationActivity);
        System.out.println("Geographical Focus: " + festival4.geographicalFocus);
        System.out.println();

        Festivals festival5 = new Festivals();
        festival5.name = "Onam";
        festival5.mainReligionCulture = "Hindu";
        festival5.typicalSeason = "Monsoon (August/September)";
        festival5.approximateDurationDays = 10;
        festival5.primaryCelebrationActivity = "Pookalam, Onam Sadya, boat races";
        festival5.geographicalFocus = "Kerala, South India";
        System.out.println("Name: " + festival5.name);
        System.out.println("Main Religion/Culture: " + festival5.mainReligionCulture);
        System.out.println("Typical Season: " + festival5.typicalSeason);
        System.out.println("Approximate Duration (Days): " + festival5.approximateDurationDays);
        System.out.println("Primary Celebration Activity: " + festival5.primaryCelebrationActivity);
        System.out.println("Geographical Focus: " + festival5.geographicalFocus);
        System.out.println();

        Festivals festival6 = new Festivals();
        festival6.name = "Pongal";
        festival6.mainReligionCulture = "Hindu";
        festival6.typicalSeason = "Winter (January)";
        festival6.approximateDurationDays = 4;
        festival6.primaryCelebrationActivity = "Harvest celebration, Pongal dish, cattle worship";
        festival6.geographicalFocus = "Tamil Nadu, South India";
        System.out.println("Name: " + festival6.name);
        System.out.println("Main Religion/Culture: " + festival6.mainReligionCulture);
        System.out.println("Typical Season: " + festival6.typicalSeason);
        System.out.println("Approximate Duration (Days): " + festival6.approximateDurationDays);
        System.out.println("Primary Celebration Activity: " + festival6.primaryCelebrationActivity);
        System.out.println("Geographical Focus: " + festival6.geographicalFocus);
        System.out.println();

        Festivals festival7 = new Festivals();
        festival7.name = "Ugadi";
        festival7.mainReligionCulture = "Hindu";
        festival7.typicalSeason = "Spring (March/April)";
        festival7.approximateDurationDays = 1;
        festival7.primaryCelebrationActivity = "New Year, Ugadi Pachadi, traditional rituals";
        festival7.geographicalFocus = "Karnataka, Andhra Pradesh, Telangana";
        System.out.println("Name: " + festival7.name);
        System.out.println("Main Religion/Culture: " + festival7.mainReligionCulture);
        System.out.println("Typical Season: " + festival7.typicalSeason);
        System.out.println("Approximate Duration (Days): " + festival7.approximateDurationDays);
        System.out.println("Primary Celebration Activity: " + festival7.primaryCelebrationActivity);
        System.out.println("Geographical Focus: " + festival7.geographicalFocus);
        System.out.println();

        Festivals festival8 = new Festivals();
        festival8.name = "Ganesh Chaturthi";
        festival8.mainReligionCulture = "Hindu";
        festival8.typicalSeason = "Monsoon (August/September)";
        festival8.approximateDurationDays = 10;
        festival8.primaryCelebrationActivity = "Idol worship, processions, modak sweets";
        festival8.geographicalFocus = "Maharashtra, Karnataka, Gujarat";
        System.out.println("Name: " + festival8.name);
        System.out.println("Main Religion/Culture: " + festival8.mainReligionCulture);
        System.out.println("Typical Season: " + festival8.typicalSeason);
        System.out.println("Approximate Duration (Days): " + festival8.approximateDurationDays);
        System.out.println("Primary Celebration Activity: " + festival8.primaryCelebrationActivity);
        System.out.println("Geographical Focus: " + festival8.geographicalFocus);
        System.out.println();

        Festivals festival9 = new Festivals();
        festival9.name = "Durga Puja";
        festival9.mainReligionCulture = "Hindu";
        festival9.typicalSeason = "Autumn (September/October)";
        festival9.approximateDurationDays = 5;
        festival9.primaryCelebrationActivity = "Pandal hopping, cultural programs, feasting";
        festival9.geographicalFocus = "West Bengal, Northeast India";
        System.out.println("Name: " + festival9.name);
        System.out.println("Main Religion/Culture: " + festival9.mainReligionCulture);
        System.out.println("Typical Season: " + festival9.typicalSeason);
        System.out.println("Approximate Duration (Days): " + festival9.approximateDurationDays);
        System.out.println("Primary Celebration Activity: " + festival9.primaryCelebrationActivity);
        System.out.println("Geographical Focus: " + festival9.geographicalFocus);
        System.out.println();

        Festivals festival10 = new Festivals();
        festival10.name = "Navaratri";
        festival10.mainReligionCulture = "Hindu";
        festival10.typicalSeason = "Autumn (September/October)";
        festival10.approximateDurationDays = 9;
        festival10.primaryCelebrationActivity = "Garba/Dandiya dances, fasting, goddess worship";
        festival10.geographicalFocus = "Gujarat, North India";
        System.out.println("Name: " + festival10.name);
        System.out.println("Main Religion/Culture: " + festival10.mainReligionCulture);
        System.out.println("Typical Season: " + festival10.typicalSeason);
        System.out.println("Approximate Duration (Days): " + festival10.approximateDurationDays);
        System.out.println("Primary Celebration Activity: " + festival10.primaryCelebrationActivity);
        System.out.println("Geographical Focus: " + festival10.geographicalFocus);
        System.out.println();

        Festivals festival11 = new Festivals();
        festival11.name = "Makar Sankranti";
        festival11.mainReligionCulture = "Hindu";
        festival11.typicalSeason = "Winter (January)";
        festival11.approximateDurationDays = 1;
        festival11.primaryCelebrationActivity = "Kite flying, sesame sweets, harvest rituals";
        festival11.geographicalFocus = "Pan-India";
        System.out.println("Name: " + festival11.name);
        System.out.println("Main Religion/Culture: " + festival11.mainReligionCulture);
        System.out.println("Typical Season: " + festival11.typicalSeason);
        System.out.println("Approximate Duration (Days): " + festival11.approximateDurationDays);
        System.out.println("Primary Celebration Activity: " + festival11.primaryCelebrationActivity);
        System.out.println("Geographical Focus: " + festival11.geographicalFocus);
        System.out.println();

        Festivals festival12 = new Festivals();
        festival12.name = "Baisakhi";
        festival12.mainReligionCulture = "Sikh, Hindu";
        festival12.typicalSeason = "Spring (April)";
        festival12.approximateDurationDays = 1;
        festival12.primaryCelebrationActivity = "Harvest festival, Nagar Kirtan, Bhangra";
        festival12.geographicalFocus = "Punjab, North India";
        System.out.println("Name: " + festival12.name);
        System.out.println("Main Religion/Culture: " + festival12.mainReligionCulture);
        System.out.println("Typical Season: " + festival12.typicalSeason);
        System.out.println("Approximate Duration (Days): " + festival12.approximateDurationDays);
        System.out.println("Primary Celebration Activity: " + festival12.primaryCelebrationActivity);
        System.out.println("Geographical Focus: " + festival12.geographicalFocus);
        System.out.println();

        Festivals festival13 = new Festivals();
        festival13.name = "Good Friday";
        festival13.mainReligionCulture = "Christian";
        festival13.typicalSeason = "Spring (March/April)";
        festival13.approximateDurationDays = 1;
        festival13.primaryCelebrationActivity = "Church services, fasting, reflection";
        festival13.geographicalFocus = "Global";
        System.out.println("Name: " + festival13.name);
        System.out.println("Main Religion/Culture: " + festival13.mainReligionCulture);
        System.out.println("Typical Season: " + festival13.typicalSeason);
        System.out.println("Approximate Duration (Days): " + festival13.approximateDurationDays);
        System.out.println("Primary Celebration Activity: " + festival13.primaryCelebrationActivity);
        System.out.println("Geographical Focus: " + festival13.geographicalFocus);
        System.out.println();

        Festivals festival14 = new Festivals();
        festival14.name = "Buddha Purnima";
        festival14.mainReligionCulture = "Buddhist";
        festival14.typicalSeason = "Spring (May)";
        festival14.approximateDurationDays = 1;
        festival14.primaryCelebrationActivity = "Prayers, meditation, processions";
        festival14.geographicalFocus = "Pan-India, Southeast Asia";
        System.out.println("Name: " + festival14.name);
        System.out.println("Main Religion/Culture: " + festival14.mainReligionCulture);
        System.out.println("Typical Season: " + festival14.typicalSeason);
        System.out.println("Approximate Duration (Days): " + festival14.approximateDurationDays);
        System.out.println("Primary Celebration Activity: " + festival14.primaryCelebrationActivity);
        System.out.println("Geographical Focus: " + festival14.geographicalFocus);
        System.out.println();

        Festivals festival15 = new Festivals();
        festival15.name = "Guru Nanak Jayanti";
        festival15.mainReligionCulture = "Sikh";
        festival15.typicalSeason = "Autumn (November)";
        festival15.approximateDurationDays = 1;
        festival15.primaryCelebrationActivity = "Kirtan, langar, processions";
        festival15.geographicalFocus = "Pan-India, Global";
        System.out.println("Name: " + festival15.name);
        System.out.println("Main Religion/Culture: " + festival15.mainReligionCulture);
        System.out.println("Typical Season: " + festival15.typicalSeason);
        System.out.println("Approximate Duration (Days): " + festival15.approximateDurationDays);
        System.out.println("Primary Celebration Activity: " + festival15.primaryCelebrationActivity);
        System.out.println("Geographical Focus: " + festival15.geographicalFocus);
        System.out.println();

        Festivals festival16 = new Festivals();
        festival16.name = "Mahavir Jayanti";
        festival16.mainReligionCulture = "Jain";
        festival16.typicalSeason = "Spring (March/April)";
        festival16.approximateDurationDays = 1;
        festival16.primaryCelebrationActivity = "Processions, prayers, charity";
        festival16.geographicalFocus = "Pan-India";
        System.out.println("Name: " + festival16.name);
        System.out.println("Main Religion/Culture: " + festival16.mainReligionCulture);
        System.out.println("Typical Season: " + festival16.typicalSeason);
        System.out.println("Approximate Duration (Days): " + festival16.approximateDurationDays);
        System.out.println("Primary Celebration Activity: " + festival16.primaryCelebrationActivity);
        System.out.println("Geographical Focus: " + festival16.geographicalFocus);
        System.out.println();

        Festivals festival17 = new Festivals();
        festival17.name = "New Year's Day";
        festival17.mainReligionCulture = "Secular, Global";
        festival17.typicalSeason = "Winter (January)";
        festival17.approximateDurationDays = 1;
        festival17.primaryCelebrationActivity = "Parties, resolutions, gatherings";
        festival17.geographicalFocus = "Global";
        System.out.println("Name: " + festival17.name);
        System.out.println("Main Religion/Culture: " + festival17.mainReligionCulture);
        System.out.println("Typical Season: " + festival17.typicalSeason);
        System.out.println("Approximate Duration (Days): " + festival17.approximateDurationDays);
        System.out.println("Primary Celebration Activity: " + festival17.primaryCelebrationActivity);
        System.out.println("Geographical Focus: " + festival17.geographicalFocus);
        System.out.println();

        Festivals festival18 = new Festivals();
        festival18.name = "Republic Day";
        festival18.mainReligionCulture = "National";
        festival18.typicalSeason = "Winter (January)";
        festival18.approximateDurationDays = 1;
        festival18.primaryCelebrationActivity = "Parades, flag hoisting, patriotic events";
        festival18.geographicalFocus = "India";
        System.out.println("Name: " + festival18.name);
        System.out.println("Main Religion/Culture: " + festival18.mainReligionCulture);
        System.out.println("Typical Season: " + festival18.typicalSeason);
        System.out.println("Approximate Duration (Days): " + festival18.approximateDurationDays);
        System.out.println("Primary Celebration Activity: " + festival18.primaryCelebrationActivity);
        System.out.println("Geographical Focus: " + festival18.geographicalFocus);
        System.out.println();

        Festivals festival19 = new Festivals();
        festival19.name = "Independence Day";
        festival19.mainReligionCulture = "National";
        festival19.typicalSeason = "Monsoon (August)";
        festival19.approximateDurationDays = 1;
        festival19.primaryCelebrationActivity = "Flag hoisting, patriotic speeches, cultural programs";
        festival19.geographicalFocus = "India";
        System.out.println("Name: " + festival19.name);
        System.out.println("Main Religion/Culture: " + festival19.mainReligionCulture);
        System.out.println("Typical Season: " + festival19.typicalSeason);
        System.out.println("Approximate Duration (Days): " + festival19.approximateDurationDays);
        System.out.println("Primary Celebration Activity: " + festival19.primaryCelebrationActivity);
        System.out.println("Geographical Focus: " + festival19.geographicalFocus);
        System.out.println();

        Festivals festival20 = new Festivals();
        festival20.name = "Gandhi Jayanti";
        festival20.mainReligionCulture = "National";
        festival20.typicalSeason = "Autumn (October)";
        festival20.approximateDurationDays = 1;
        festival20.primaryCelebrationActivity = "Prayer meetings, tributes, non-violence awareness";
        festival20.geographicalFocus = "India";
        System.out.println("Name: " + festival20.name);
        System.out.println("Main Religion/Culture: " + festival20.mainReligionCulture);
        System.out.println("Typical Season: " + festival20.typicalSeason);
        System.out.println("Approximate Duration (Days): " + festival20.approximateDurationDays);
        System.out.println("Primary Celebration Activity: " + festival20.primaryCelebrationActivity);
        System.out.println("Geographical Focus: " + festival20.geographicalFocus);
        System.out.println();

        System.out.println("Main Ended - Festivals Data Display Complete");
    }
}
