class GiTagRunner {
    public static void main(String[] args) {
        System.out.println("Main Started - GiTag Data");

        GiTag gi1 = new GiTag();
        gi1.name = "Mysore Silk";
        gi1.category = "Handicrafts";
        gi1.geographicalArea = "Mysuru, Karnataka";
        gi1.registrationYear = 2005;
        gi1.description = "Traditional silk sarees known for their purity and intricate zari work.";
        gi1.registeredHolder = "Karnataka Silk Industries Corporation (KSIC)";
        System.out.println("Name: " + gi1.name);
        System.out.println("Category: " + gi1.category);
        System.out.println("Geographical Area: " + gi1.geographicalArea);
        System.out.println("Registration Year: " + gi1.registrationYear);
        System.out.println("Description: " + gi1.description);
        System.out.println("Registered Holder: " + gi1.registeredHolder);
        System.out.println();

        GiTag gi2 = new GiTag();
        gi2.name = "Coorg Arabica Coffee";
        gi2.category = "Agricultural";
        gi2.geographicalArea = "Kodagu District, Karnataka";
        gi2.registrationYear = 2017;
        gi2.description = "Coffee grown in the hilly tracts of Kodagu, known for its mild flavor and aroma.";
        gi2.registeredHolder = "Coffee Board";
        System.out.println("Name: " + gi2.name);
        System.out.println("Category: " + gi2.category);
        System.out.println("Geographical Area: " + gi2.geographicalArea);
        System.out.println("Registration Year: " + gi2.registrationYear);
        System.out.println("Description: " + gi2.description);
        System.out.println("Registered Holder: " + gi2.registeredHolder);
        System.out.println();

        GiTag gi3 = new GiTag();
        gi3.name = "Bidriware";
        gi3.category = "Handicrafts";
        gi3.geographicalArea = "Bidar, Karnataka";
        gi3.registrationYear = 2008;
        gi3.description = "Metal handicraft from Bidar, known for its unique silver inlay work on a blackened alloy.";
        gi3.registeredHolder = "Karnataka State Handicrafts Development Corporation Ltd.";
        System.out.println("Name: " + gi3.name);
        System.out.println("Category: " + gi3.category);
        System.out.println("Geographical Area: " + gi3.geographicalArea);
        System.out.println("Registration Year: " + gi3.registrationYear);
        System.out.println("Description: " + gi3.description);
        System.out.println("Registered Holder: " + gi3.registeredHolder);
        System.out.println();

        GiTag gi4 = new GiTag();
        gi4.name = "Channapatna Toys & Dolls";
        gi4.category = "Handicrafts";
        gi4.geographicalArea = "Channapatna, Karnataka";
        gi4.registrationYear = 2005;
        gi4.description = "Traditional wooden toys and dolls, lacquered with natural dyes.";
        gi4.registeredHolder = "Karnataka State Handicrafts Development Corporation Ltd.";
        System.out.println("Name: " + gi4.name);
        System.out.println("Category: " + gi4.category);
        System.out.println("Geographical Area: " + gi4.geographicalArea);
        System.out.println("Registration Year: " + gi4.registrationYear);
        System.out.println("Description: " + gi4.description);
        System.out.println("Registered Holder: " + gi4.registeredHolder);
        System.out.println();

        GiTag gi5 = new GiTag();
        gi5.name = "Mysore Pak";
        gi5.category = "Foodstuff";
        gi5.geographicalArea = "Mysuru, Karnataka";
        gi5.registrationYear = 2019; // Example year, actual GI status is debated/pending
        gi5.description = "A sweet dish made from gram flour, ghee, and sugar, originating from the Mysore Palace kitchen.";
        gi5.registeredHolder = "Mysore Palace Board (Proposed)";
        System.out.println("Name: " + gi5.name);
        System.out.println("Category: " + gi5.category);
        System.out.println("Geographical Area: " + gi5.geographicalArea);
        System.out.println("Registration Year: " + gi5.registrationYear);
        System.out.println("Description: " + gi5.description);
        System.out.println("Registered Holder: " + gi5.registeredHolder);
        System.out.println();

        GiTag gi6 = new GiTag();
        gi6.name = "Udupi Sarees";
        gi6.category = "Textile";
        gi6.geographicalArea = "Udupi, Karnataka";
        gi6.registrationYear = 2016;
        gi6.description = "Handloom cotton sarees known for their unique weaving technique and vibrant colors.";
        gi6.registeredHolder = "Udupi Handloom Weavers' Cooperative Society Ltd.";
        System.out.println("Name: " + gi6.name);
        System.out.println("Category: " + gi6.category);
        System.out.println("Geographical Area: " + gi6.geographicalArea);
        System.out.println("Registration Year: " + gi6.registrationYear);
        System.out.println("Description: " + gi6.description);
        System.out.println("Registered Holder: " + gi6.registeredHolder);
        System.out.println();

        GiTag gi7 = new GiTag();
        gi7.name = "Bangalore Blue Grapes";
        gi7.category = "Agricultural";
        gi7.geographicalArea = "Bengaluru Rural, Karnataka";
        gi7.registrationYear = 2013;
        gi7.description = "A specific variety of grape known for its distinct foxy flavor, grown around Bangalore.";
        gi7.registeredHolder = "Karnataka Grape Growers' Association";
        System.out.println("Name: " + gi7.name);
        System.out.println("Category: " + gi7.category);
        System.out.println("Geographical Area: " + gi7.geographicalArea);
        System.out.println("Registration Year: " + gi7.registrationYear);
        System.out.println("Description: " + gi7.description);
        System.out.println("Registered Holder: " + gi7.registeredHolder);
        System.out.println();

        GiTag gi8 = new GiTag();
        gi8.name = "Kinnal Toys";
        gi8.category = "Handicrafts";
        gi8.geographicalArea = "Kinnal, Koppal District, Karnataka";
        gi8.registrationYear = 2012;
        gi8.description = "Traditional wooden toys and religious idols, known for their lightweight and vibrant colors.";
        gi8.registeredHolder = "Karnataka State Handicrafts Development Corporation Ltd.";
        System.out.println("Name: " + gi8.name);
        System.out.println("Category: " + gi8.category);
        System.out.println("Geographical Area: " + gi8.geographicalArea);
        System.out.println("Registration Year: " + gi8.registrationYear);
        System.out.println("Description: " + gi8.description);
        System.out.println("Registered Holder: " + gi8.registeredHolder);
        System.out.println();

        GiTag gi9 = new GiTag();
        gi9.name = "Mysore Agarbathi";
        gi9.category = "Manufactured";
        gi9.geographicalArea = "Mysuru, Karnataka";
        gi9.registrationYear = 2005;
        gi9.description = "Incense sticks known for their unique fragrance blends and traditional manufacturing process.";
        gi9.registeredHolder = "All India Agarbathi Manufacturers Association";
        System.out.println("Name: " + gi9.name);
        System.out.println("Category: " + gi9.category);
        System.out.println("Geographical Area: " + gi9.geographicalArea);
        System.out.println("Registration Year: " + gi9.registrationYear);
        System.out.println("Description: " + gi9.description);
        System.out.println("Registered Holder: " + gi9.registeredHolder);
        System.out.println();

        GiTag gi10 = new GiTag();
        gi10.name = "Ilkal Sarees";
        gi10.category = "Textile";
        gi10.geographicalArea = "Ilkal, Bagalkot District, Karnataka";
        gi10.registrationYear = 2007;
        gi10.description = "Traditional handloom sarees characterized by their unique pallu design and border.";
        gi10.registeredHolder = "Ilkal Handloom Weavers' Association";
        System.out.println("Name: " + gi10.name);
        System.out.println("Category: " + gi10.category);
        System.out.println("Geographical Area: " + gi10.geographicalArea);
        System.out.println("Registration Year: " + gi10.registrationYear);
        System.out.println("Description: " + gi10.description);
        System.out.println("Registered Holder: " + gi10.registeredHolder);
        System.out.println();

        GiTag gi11 = new GiTag();
        gi11.name = "Byadagi Chilli";
        gi11.category = "Agricultural";
        gi11.geographicalArea = "Byadagi, Haveri District, Karnataka";
        gi11.registrationYear = 2011;
        gi11.description = "A famous variety of red chilli known for its deep red color and low pungency.";
        gi11.registeredHolder = "Byadagi Chilli Growers' Association";
        System.out.println("Name: " + gi11.name);
        System.out.println("Category: " + gi11.category);
        System.out.println("Geographical Area: " + gi11.geographicalArea);
        System.out.println("Registration Year: " + gi11.registrationYear);
        System.out.println("Description: " + gi11.description);
        System.out.println("Registered Holder: " + gi11.registeredHolder);
        System.out.println();

        GiTag gi12 = new GiTag();
        gi12.name = "Ganjifa Cards";
        gi12.category = "Handicrafts";
        gi12.geographicalArea = "Mysuru, Karnataka";
        gi12.registrationYear = 2008;
        gi12.description = "Traditional Indian playing cards, hand-painted with intricate designs.";
        gi12.registeredHolder = "Karnataka State Handicrafts Development Corporation Ltd.";
        System.out.println("Name: " + gi12.name);
        System.out.println("Category: " + gi12.category);
        System.out.println("Geographical Area: " + gi12.geographicalArea);
        System.out.println("Registration Year: " + gi12.registrationYear);
        System.out.println("Description: " + gi12.description);
        System.out.println("Registered Holder: " + gi12.registeredHolder);
        System.out.println();

        GiTag gi13 = new GiTag();
        gi13.name = "Navalgund Durries";
        gi13.category = "Handicrafts";
        gi13.geographicalArea = "Navalgund, Dharwad District, Karnataka";
        gi13.registrationYear = 2011;
        gi13.description = "Hand-woven floor coverings known for their geometric patterns and vibrant colors.";
        gi13.registeredHolder = "Navalgund Durries Weavers' Association";
        System.out.println("Name: " + gi13.name);
        System.out.println("Category: " + gi13.category);
        System.out.println("Geographical Area: " + gi13.geographicalArea);
        System.out.println("Registration Year: " + gi13.registrationYear);
        System.out.println("Description: " + gi13.description);
        System.out.println("Registered Holder: " + gi13.registeredHolder);
        System.out.println();

        GiTag gi14 = new GiTag();
        gi14.name = "Mysore Traditional Paintings";
        gi14.category = "Handicrafts";
        gi14.geographicalArea = "Mysuru, Karnataka";
        gi14.registrationYear = 2005;
        gi14.description = "Classical South Indian paintings known for their elegance, muted colors, and attention to detail.";
        gi14.registeredHolder = "Karnataka State Handicrafts Development Corporation Ltd.";
        System.out.println("Name: " + gi14.name);
        System.out.println("Category: " + gi14.category);
        System.out.println("Geographical Area: " + gi14.geographicalArea);
        System.out.println("Registration Year: " + gi14.registrationYear);
        System.out.println("Description: " + gi14.description);
        System.out.println("Registered Holder: " + gi14.registeredHolder);
        System.out.println();

        GiTag gi15 = new GiTag();
        gi15.name = "Bangalore Rose Onion";
        gi15.category = "Agricultural";
        gi15.geographicalArea = "Bengaluru Rural, Karnataka";
        gi15.registrationYear = 2015;
        gi15.description = "A unique variety of onion known for its distinct pungency and rosy red color.";
        gi15.registeredHolder = "Bangalore Rose Onion Growers' Association";
        System.out.println("Name: " + gi15.name);
        System.out.println("Category: " + gi15.category);
        System.out.println("Geographical Area: " + gi15.geographicalArea);
        System.out.println("Registration Year: " + gi15.registrationYear);
        System.out.println("Description: " + gi15.description);
        System.out.println("Registered Holder: " + gi15.registeredHolder);
        System.out.println();

        GiTag gi16 = new GiTag();
        gi16.name = "Nanjangud Banana";
        gi16.category = "Agricultural";
        gi16.geographicalArea = "Nanjangud, Mysuru District, Karnataka";
        gi16.registrationYear = 2015;
        gi16.description = "A sweet and aromatic banana variety, unique to the Nanjangud region.";
        gi16.registeredHolder = "Nanjangud Banana Growers' Association";
        System.out.println("Name: " + gi16.name);
        System.out.println("Category: " + gi16.category);
        System.out.println("Geographical Area: " + gi16.geographicalArea);
        System.out.println("Registration Year: " + gi16.registrationYear);
        System.out.println("Description: " + gi16.description);
        System.out.println("Registered Holder: " + gi16.registeredHolder);
        System.out.println();

        GiTag gi17 = new GiTag();
        gi17.name = "Malabar Pepper";
        gi17.category = "Agricultural";
        gi17.geographicalArea = "Malabar Region, Karnataka & Kerala";
        gi17.registrationYear = 2008;
        gi17.description = "High-quality black pepper from the Malabar coast, known for its strong aroma and flavor.";
        gi17.registeredHolder = "Spices Board of India";
        System.out.println("Name: " + gi17.name);
        System.out.println("Category: " + gi17.category);
        System.out.println("Geographical Area: " + gi17.geographicalArea);
        System.out.println("Registration Year: " + gi17.registrationYear);
        System.out.println("Description: " + gi17.description);
        System.out.println("Registered Holder: " + gi17.registeredHolder);
        System.out.println();

        GiTag gi18 = new GiTag();
        gi18.name = "Coorg Orange";
        gi18.category = "Agricultural";
        gi18.geographicalArea = "Kodagu District, Karnataka";
        gi18.registrationYear = 2005;
        gi18.description = "A specific variety of orange grown in Coorg, known for its distinct taste and aroma.";
        gi18.registeredHolder = "Coorg Orange Growers' Association";
        System.out.println("Name: " + gi18.name);
        System.out.println("Category: " + gi18.category);
        System.out.println("Geographical Area: " + gi18.geographicalArea);
        System.out.println("Registration Year: " + gi18.registrationYear);
        System.out.println("Description: " + gi18.description);
        System.out.println("Registered Holder: " + gi18.registeredHolder);
        System.out.println();

        GiTag gi19 = new GiTag();
        gi19.name = "Dharwad Pedha";
        gi19.category = "Foodstuff";
        gi19.geographicalArea = "Dharwad, Karnataka";
        gi19.registrationYear = 2007;
        gi19.description = "A traditional sweet made from milk, sugar, and khoa, famous for its unique taste and texture.";
        gi19.registeredHolder = "Thakur Pedha Private Limited";
        System.out.println("Name: " + gi19.name);
        System.out.println("Category: " + gi19.category);
        System.out.println("Geographical Area: " + gi19.geographicalArea);
        System.out.println("Registration Year: " + gi19.registrationYear);
        System.out.println("Description: " + gi19.description);
        System.out.println("Registered Holder: " + gi19.registeredHolder);
        System.out.println();

        GiTag gi20 = new GiTag();
        gi20.name = "Mysore Sandal Soap";
        gi20.category = "Manufactured";
        gi20.geographicalArea = "Mysuru, Karnataka";
        gi20.registrationYear = 2011;
        gi20.description = "A soap made from pure sandalwood oil, produced by Karnataka Soaps and Detergents Limited.";
        gi20.registeredHolder = "Karnataka Soaps and Detergents Limited";
        System.out.println("Name: " + gi20.name);
        System.out.println("Category: " + gi20.category);
        System.out.println("Geographical Area: " + gi20.geographicalArea);
        System.out.println("Registration Year: " + gi20.registrationYear);
        System.out.println("Description: " + gi20.description);
        System.out.println("Registered Holder: " + gi20.registeredHolder);
        System.out.println();

        System.out.println("Main Ended - GiTag Data Display Complete");
    }
}
