class GymEquipmentRunner {
    public static void main(String[] args) {

        GymEquipment e1 = new GymEquipment();
        e1.name = "Treadmill";
        e1.type = "Cardio";
        e1.brand = "PowerMax";
        e1.weight = 90.5;
        e1.price = 45000;
        e1.isElectronic = true;
		System.out.println("The name is "+e1.name);
		System.out.println("The type is "+e1.type);
		System.out.println("The brand is "+e1.brand);
		System.out.println("The weight is "+e1.weight);
		System.out.println("The price is "+e1.price);
		System.out.println("The electronic is "+e3.isElectronic);

        GymEquipment e2 = new GymEquipment();
        e2.name = "Dumbbell";
        e2.type = "Strength";
        e2.brand = "Kobo";
        e2.weight = 10;
        e2.price = 1200;
        e2.isElectronic = false;
		System.out.println("The name is "+e3.name);
		System.out.println("The type is "+e3.type);
		System.out.println("The brand is "+e3.brand);
		System.out.println("The weight is "+e3.weight);
		System.out.println("The price is "+e3.price);
		System.out.println("The electronic is "+e3.isElectronic);

        GymEquipment e3 = new GymEquipment();
        e3.name = "Exercise Bike";
        e3.type = "Cardio";
        e3.brand = "Fitkit";
        e3.weight = 35.7;
        e3.price = 25000;
        e3.isElectronic = true;
		System.out.println("The name is "+e4.name);
		System.out.println("The type is "+e4.type);
		System.out.println("The brand is "+e4.brand);
		System.out.println("The weight is "+e4.weight);
		System.out.println("The price is "+e4.price);
		System.out.println("The electronic is "+e4.isElectronic);

        GymEquipment e4 = new GymEquipment();
        e4.name = "Rowing Machine";
        e4.type = "Cardio";
        e4.brand = "Concept2";
        e4.weight = 57;
        e4.price = 75000;
        e4.isElectronic = true;
		System.out.println("The name is "+e5.name);
		System.out.println("The type is "+e5.type);
		System.out.println("The brand is "+e5.brand);
		System.out.println("The weight is "+e5.weight);
		System.out.println("The price is "+e5.price);
		System.out.println("The electronic is "+e5.isElectronic);

        GymEquipment e5 = new GymEquipment();
        e5.name = "Kettlebell";
        e5.type = "Strength";
        e5.brand = "Protoner";
        e5.weight = 12;
        e5.price = 1500;
        e5.isElectronic = false;
		System.out.println("The name is "+e6.name);
		System.out.println("The type is "+e6.type);
		System.out.println("The brand is "+e6.brand);
		System.out.println("The weight is "+e6.weight);
		System.out.println("The price is "+e6.price);
		System.out.println("The electronic is "+e6.isElectronic);

        GymEquipment e6 = new GymEquipment();
        e6.name = "Elliptical Cross Trainer";
        e6.type = "Cardio";
        e6.brand = "Reebok";
        e6.weight = 45;
        e6.price = 30000;
        e6.isElectronic = true;
		System.out.println("The name is "+e7.name);
		System.out.println("The type is "+e7.type);
		System.out.println("The brand is "+e7.brand);
		System.out.println("The weight is "+e7.weight);
		System.out.println("The price is "+e7.price);
		System.out.println("The electronic is "+e7.isElectronic);

        GymEquipment e7 = new GymEquipment();
        e7.name = "Leg Press Machine";
        e7.type = "Strength";
        e7.brand = "BodySolid";
        e7.weight = 100;
        e7.price = 55000;
        e7.isElectronic = false;
		System.out.println("The name is "+e8.name);
		System.out.println("The type is "+e8.type);
		System.out.println("The brand is "+e8.brand);
		System.out.println("The weight is "+e8.weight);
		System.out.println("The price is "+e8.price);
		System.out.println("The electronic is "+e8.isElectronic);

        GymEquipment e8 = new GymEquipment();
        e8.name = "Smith Machine";
        e8.type = "Strength";
        e8.brand = "Cosco";
        e8.weight = 120;
        e8.price = 80000;
        e8.isElectronic = false;
		System.out.println("The name is "+e9.name);
		System.out.println("The type is "+e9.type);
		System.out.println("The brand is "+e9.brand);
		System.out.println("The weight is "+e9.weight);
		System.out.println("The price is "+e9.price);
		System.out.println("The electronic is "+e9.isElectronic);

        GymEquipment e9 = new GymEquipment();
        e9.name = "Ab Crunch Machine";
        e9.type = "Core";
        e9.brand = "Domyos";
        e9.weight = 30;
        e9.price = 18000;
        e9.isElectronic = false;
		System.out.println("The name is "+e10.name);
		System.out.println("The type is "+e10.type);
		System.out.println("The brand is "+e10.brand);
		System.out.println("The weight is "+e10.weight);
		System.out.println("The price is "+e10.price);
		System.out.println("The electronic is "+e10.isElectronic);

        GymEquipment e10 = new GymEquipment();
        e10.name = "Chest Press";
        e10.type = "Strength";
        e10.brand = "Lifeline";
        e10.weight = 75;
        e10.price = 60000;
        e10.isElectronic = false;
		System.out.println("The name is "+e11.name);
		System.out.println("The type is "+e11.type);
		System.out.println("The brand is "+e11.brand);
		System.out.println("The weight is "+e11.weight);
		System.out.println("The price is "+e11.price);
		System.out.println("The electronic is "+e11.isElectronic);

        GymEquipment e11 = new GymEquipment();
        e11.name = "Lat Pulldown";
        e11.type = "Strength";
        e11.brand = "BodyCraft";
        e11.weight = 80;
        e11.price = 48000;
        e11.isElectronic = false;
		System.out.println("The name is "+e12.name);
		System.out.println("The type is "+e12.type);
		System.out.println("The brand is "+e12.brand);
		System.out.println("The weight is "+e12.weight);
		System.out.println("The price is "+e12.price);
		System.out.println("The electronic is "+e12.isElectronic);

        GymEquipment e12 = new GymEquipment();
        e12.name = "Stepper Machine";
        e12.type = "Cardio";
        e12.brand = "Fitkit";
        e12.weight = 40;
        e12.price = 27000;
        e12.isElectronic = true;
		System.out.println("The name is "+e13.name);
		System.out.println("The type is "+e13.type);
		System.out.println("The brand is "+e13.brand);
		System.out.println("The weight is "+e13.weight);
		System.out.println("The price is "+e13.price);
		System.out.println("The electronic is "+e13.isElectronic);

        GymEquipment e13 = new GymEquipment();
        e13.name = "Medicine Ball";
        e13.type = "Strength";
        e13.brand = "Nivia";
        e13.weight = 5;
        e13.price = 700;
        e13.isElectronic = false;
		System.out.println("The name is "+e14.name);
		System.out.println("The type is "+e14.type);
		System.out.println("The brand is "+e14.brand);
		System.out.println("The weight is "+e14.weight);
		System.out.println("The price is "+e14.price);
		System.out.println("The electronic is "+e14.isElectronic);

        GymEquipment e14 = new GymEquipment();
        e14.name = "Resistance Band";
        e14.type = "Strength";
        e14.brand = "Boldfit";
        e14.weight = 0.3;
        e14.price = 350;
        e14.isElectronic = false;
		System.out.println("The name is "+e15.name);
		System.out.println("The type is "+e15.type);
		System.out.println("The brand is "+e15.brand);
		System.out.println("The weight is "+e15.weight);
		System.out.println("The price is "+e15.price);
		System.out.println("The electronic is "+e15.isElectronic);

        GymEquipment e15 = new GymEquipment();
        e15.name = "Foam Roller";
        e15.type = "Recovery";
        e15.brand = "Strauss";
        e15.weight = 0.9;
        e15.price = 899;
        e15.isElectronic = false;
		System.out.println("The name is "+e16.name);
		System.out.println("The type is "+e16.type);
		System.out.println("The brand is "+e16.brand);
		System.out.println("The weight is "+e16.weight);
		System.out.println("The price is "+e16.price);
		System.out.println("The electronic is "+e16.isElectronic);

        GymEquipment e16 = new GymEquipment();
        e16.name = "Punching Bag";
        e16.type = "Boxing";
        e16.brand = "USI";
        e16.weight = 40;
        e16.price = 3200;
        e16.isElectronic = false;

        GymEquipment e17 = new GymEquipment();
        e17.name = "Battle Ropes";
        e17.type = "HIIT";
        e17.brand = "Kore";
        e17.weight = 15;
        e17.price = 2500;
        e17.isElectronic = false;
		System.out.println("The name is "+e17.name);
		System.out.println("The type is "+e17.type);
		System.out.println("The brand is "+e17.brand);
		System.out.println("The weight is "+e17.weight);
		System.out.println("The price is "+e17.price);
		System.out.println("The electronic is "+e17.isElectronic);

        GymEquipment e18 = new GymEquipment();
        e18.name = "Pull-Up Bar";
        e18.type = "Strength";
        e18.brand = "AmazonBasics";
        e18.weight = 5;
        e18.price = 1400;
        e18.isElectronic = false;
		System.out.println("The name is "+e18.name);
		System.out.println("The type is "+e18.type);
		System.out.println("The brand is "+e18.brand);
		System.out.println("The weight is "+e18.weight);
		System.out.println("The price is "+e18.price);
		System.out.println("The electronic is "+e18.isElectronic);

        GymEquipment e19 = new GymEquipment();
        e19.name = "Vibration Plate";
        e19.type = "Recovery";
        e19.brand = "Lifelong";
        e19.weight = 20;
        e19.price = 18000;
        e19.isElectronic = true;
		System.out.println("The name is "+e19.name);
		System.out.println("The type is "+e19.type);
		System.out.println("The brand is "+e19.brand);
		System.out.println("The weight is "+e19.weight);
		System.out.println("The price is "+e19.price);
		System.out.println("The electronic is "+e19.isElectronic);

        GymEquipment e20 = new GymEquipment();
        e20.name = "Power Rack";
        e20.type = "Strength";
        e20.brand = "Proline";
        e20.weight = 150;
        e20.price = 95000;
        e20.isElectronic = false;
		System.out.println("The name is "+e20.name);
		System.out.println("The type is "+e20.type);
		System.out.println("The brand is "+e20.brand);
		System.out.println("The weight is "+e20.weight);
		System.out.println("The price is "+e20.price);
		System.out.println("The electronic is "+e20.isElectronic);
    }
}
