public class Temple {
	    static String name ;
       static String deity ;
       static String location;
       static String style;
       static String festival;
       static String founder;
       static String materialsUsed;
       static String status ;
       static String timings;
       static String dressCode;
       static int heightFeet;
       static int builtYear;
       static int dailyVisitors;
       static int sculptures;
       static int priests;
       static int towers;
       static int mandapams;
       static int poojasPerDay;
       static int languagesSupported;
        static int donationBoxes ;
        static long templeID ;
        static long annualVisitors;
    public static void main(String[] args) {
        name = "Anjaneya Temple";
        deity = "Anjaneya";
        location = "Bedara Hosahalli, Shimoga";
        style = "Dravidian Architecture";
        festival = "Rama Navami";
        founder = "Manjunath";
        materialsUsed = "Granite";
        status = "UNESCO World Heritage Site";
        timings = "6 AM - 10 AM" + "6 PM - 7 PM";
        dressCode = "Traditional Indian Attire";
        heightFeet = 50;
        builtYear = 2025;
         dailyVisitors = 50;
        sculptures = 400;
        priests = 2;
        towers = 3;
        mandapams = 1;
        poojasPerDay = 2;
        languagesSupported = 1;
         donationBoxes = 2;
        templeID = 5678912345L;
        annualVisitors = 15000L;

        System.out.println("Temple Details ");
        System.out.println( name);
        System.out.println( deity);
        System.out.println(location);
        System.out.println( style);
        System.out.println(festival);
        System.out.println(founder);
        System.out.println(materialsUsed);
        System.out.println(status);
        System.out.println(timings);
        System.out.println(dressCode);
        System.out.println(heightFeet);
        System.out.println(builtYear);
        System.out.println(dailyVisitors);
        System.out.println( annualVisitors);
        System.out.println(sculptures);
        System.out.println( priests);
        System.out.println(towers);
        System.out.println(mandapams);
        System.out.println(poojasPerDay);
        System.out.println( donationBoxes);
        System.out.println(templeID);
    }
}
