public class VideoGames {
	static String title;
       static String genre;
       static String developer;
       static String publisher;
       static String platform;
       static String engine;
       static String director;
       static String composer;
       static String mode;
       static String difficulty;
       static int releaseYear;
       static int rating;
       static int gameLengthHours;
       static int numberOfPlayers;
       static int bosses;
       static int languagesSupported;
       static int updatesReleased;
       static int levels;
       static int awardsWon;
       static int priceUSD;
       static long downloads ;
        static long gameID ;
    public static void main(String[] args) {
        title = "Elden Ring";
        genre = "Action RPG";
        developer = "FromSoftware";
        publisher = "Bandai Namco";
        platform = "PC, PS5, Xbox";
      engine = "Proprietary Engine";
        director = "Hidetaka Miyazaki";
         composer = "Yuka Kitamura";
       mode = "Single Player";
         difficulty = "Hard";
        releaseYear = 2022;
         rating = 10;
       gameLengthHours = 80;
         numberOfPlayers = 1;
         bosses = 120;
         languagesSupported = 15;
         updatesReleased = 5;
         levels = 100;
         awardsWon = 20;
         priceUSD = 60;
        downloads = 15000000L;
         gameID = 1001002003L;

        System.out.println("Video Game Details");
        System.out.println(title);
        System.out.println( genre);
        System.out.println(developer);
        System.out.println(publisher);
        System.out.println( platform);
        System.out.println(engine);
        System.out.println(director);
        System.out.println(composer);
        System.out.println(mode);
        System.out.println(difficulty);
        System.out.println(releaseYear);
        System.out.println(rating);
        System.out.println(gameLengthHours );
        System.out.println(numberOfPlayers);
        System.out.println( bosses);
        System.out.println(languagesSupported);
        System.out.println( updatesReleased);
        System.out.println(levels);
        System.out.println(awardsWon);
        System.out.println(priceUSD);
        System.out.println(downloads);
        System.out.println(gameID);
    }
}
